name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lidorlg/dockerworkshop:${{ github.run_number }}

    - name: push the Image
      run: docker push lidorlg/dockerworkshop:${{ github.run_number }}
